typography_spectrum: 0.51686
color:
  brandColors:
    - '#fec485'
    - '#6d8c8c'
    - '#31616b'
    - '#98a598'
    - '#bbb59f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.702
analytics:
  google: null
  facebook: null
  twitter: null
name: Jonas Marczy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
