name: Jonas Marczy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11919701262377203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e5c4a'
    - '#f2e76d'
    - '#2c322c'
    - '#90896b'
    - '#0a100f'
  brandStrength: 0.5
  lightness: 0.9835386315826327
  saturation: 0.167996640317142
  rhythmicContrast: 1
purpose: []
