typography_spectrum: 0.598488278221339
color:
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  brandStrength: 0.6162217450328171
  lightness: 0.44785754987969995
  saturation: 0.8231540736742318
  rhythmicContrast: 0.5291478894650936
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06460165604948997
analytics:
  google: null
  facebook: null
  twitter: null
name: Jonas Marczy
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Test Menu Item
    id: 21139567-db67-40f2-9085-5feaa8395868
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Changes
description: Only what matters...
purpose: []
