analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.16058
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#FEF8D4'
    - '#201B17'
    - '#5F5849'
    - '#AA9983'
    - '#B4100E'
  lightness: 1
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Jonas Marczy
typography_spectrum: 0.6729323
